# -*- coding: utf-8 -*-
"""Weather API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EGJ7QGbGygocldhLLISnJ_eJqILN-DS6
"""

#pip install requests
import requests
#import os
from datetime import datetime

api_key = '3e8218e9454bd165eb4c191c50d15b6b'
	
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")
print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

#Saving the Weather Stats in weather.txt
with open('weather.txt', 'w') as f:
  f.write("-------------------------------------------------------------\n")
  f.write('Weather Stats for - {}  || {}\n'.format(location.upper(), date_time))
  f.write('-------------------------------------------------------------\n')
  f.write('Current temperature is: {:.2f} deg C\n'.format(temp_city))
  f.write('Current weather desc  : {}\n'.format(weather_desc))
  f.write("Current Humidity      : {} %\n".format(hmdt))
  f.write("Current wind speed    : {} kmph\n".format(wind_spd))
  f.close()